### ISSUE TITLE
Automatic backups #124 continued

### ISSUE THREAD

**Issue by PaulMerk** [jokay/docker-ccu-historian#126] opened 2021-10-08 12:27 UTC
first of all, backup is working now for me

I had to replace within the instruction line in the configuration "**_/db_**" by "**_/database_**" 

Misleading for me were the differences in names. On my docker installation, the database is stored in directory  _/docker/historian/db_, while in ccu-historian.config it is named /database (database.dir='/database').

Logging
in directory docker/historian/db/log is visible for me now with corresponding adjustments in the config file
logSystem.fileName='/database/log/ccu-historian-%g.log' while the directory on the server is named /docker/historian/db/log

Syntax for external storage
In some cases it might be helpful to have the syntax available, in case a different server for storage is preferred.
Thanks
Paul

**Comment by jokay** [comment] 2021-10-10 06:57
Issue closed, duplicate of #124 *(issues can be reopened)*.

For me it seems it's more of a [Docker volumes](https://docs.docker.com/storage/volumes/) know-how issue instead of a problem with this container.

**Closed by jokay** 2021-10-10 06:57 UTC
